/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: nimzu (https://sketchfab.com/nimzuk)
License: CC-BY-4.0
Source: https://sketchfab.com/3d-models/foxs-islands-163b68e09fcc47618450150be7785907
Title: Fox's islands
*/

import { useRef, useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";
import { a } from "@react-spring/three";

import islandScene from "../assets/3d/island.glb";

const Island = ({ isRotating, setIsRotating, setCurrentStage, ...props }) => {
  const islandRef = useRef();

  const { gl } = useThree();
  const { nodes, materials } = useGLTF(islandScene);

  const lastX = useRef(0);
  const velocity = useRef(0);
  const activePointerId = useRef(null);

  const DAMPING = 0.94;
  const ROTATION_FACTOR = 2.0; // 🔥 works on both mobile & desktop

  /* ---------------- POINTER EVENTS ---------------- */

  const onPointerDown = (e) => {
    e.preventDefault();

    activePointerId.current = e.pointerId;
    gl.domElement.setPointerCapture(e.pointerId);

    setIsRotating(true);
    lastX.current = e.clientX;
    velocity.current = 0; // kill old momentum
  };

  const onPointerMove = (e) => {
    if (!isRotating) return;
    if (e.pointerId !== activePointerId.current) return;

    const canvasWidth = gl.domElement.clientWidth;
    const deltaX = (e.clientX - lastX.current) / canvasWidth;

    const rotationDelta = deltaX * Math.PI * ROTATION_FACTOR;

    islandRef.current.rotation.y += rotationDelta;
    velocity.current = rotationDelta;

    lastX.current = e.clientX;
  };

  const onPointerUp = (e) => {
    if (e.pointerId !== activePointerId.current) return;

    gl.domElement.releasePointerCapture(e.pointerId);
    activePointerId.current = null;

    setIsRotating(false);
  };

  /* ---------------- EVENTS ---------------- */

  useEffect(() => {
    const canvas = gl.domElement;

    canvas.addEventListener("pointerdown", onPointerDown);
    canvas.addEventListener("pointermove", onPointerMove);
    canvas.addEventListener("pointerup", onPointerUp);
    canvas.addEventListener("pointercancel", onPointerUp);

    return () => {
      canvas.removeEventListener("pointerdown", onPointerDown);
      canvas.removeEventListener("pointermove", onPointerMove);
      canvas.removeEventListener("pointerup", onPointerUp);
      canvas.removeEventListener("pointercancel", onPointerUp);
    };
  }, [gl, isRotating]);

  /* ---------------- FRAME LOOP ---------------- */

  useFrame(() => {
    if (!isRotating) {
      velocity.current *= DAMPING;

      if (Math.abs(velocity.current) < 0.0001) {
        velocity.current = 0;
      }

      islandRef.current.rotation.y += velocity.current;
    }

    // stage detection (unchanged)
    const r = islandRef.current.rotation.y;
    const n = ((r % (2 * Math.PI)) + 2 * Math.PI) % (2 * Math.PI);

    switch (true) {
      case n >= 5.45 && n <= 5.85:
        setCurrentStage(4);
        break;
      case n >= 0.85 && n <= 1.3:
        setCurrentStage(3);
        break;
      case n >= 2.4 && n <= 2.6:
        setCurrentStage(2);
        break;
      case n >= 4.25 && n <= 4.75:
        setCurrentStage(1);
        break;
      default:
        setCurrentStage(null);
    }
  });

  /* ---------------- MODEL ---------------- */

  return (
    <a.group ref={islandRef} {...props}>
      <mesh geometry={nodes.polySurface944_tree_body_0.geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes.polySurface945_tree1_0.geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes.polySurface946_tree2_0.geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes.polySurface947_tree1_0.geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes.polySurface948_tree_body_0.geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes.polySurface949_tree_body_0.geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes.pCube11_rocks1_0.geometry} material={materials.PaletteMaterial001} />
    </a.group>
  );
};

export default Island;
